substitutions:
  name: esphome-web-b1c8eb
  friendly_name: uniPCB1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev
  on_boot:
    priority: 600
    # ...
    then:
      - delay: 1s
      - switch.turn_on: mailbox


esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QgF2dwnmDJLfeKKlyFtLZy0lw+llgxOlvpNLNCeNmEU="

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

binary_sensor:
  - platform: gpio
    name: "Defeat"
    id: "defeat"
    pin:
      number: 2
      mode: INPUT
    on_press:
      then:
        - logger.log: "Prevent deep sleep"
        - deep_sleep.prevent: deep_sleep_1

switch:
  - platform: gpio
    pin: GPIO12
    id: mailbox
    name: "Mailbox"

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    accuracy_decimals: 1
    filters:
      - multiply: 1

  - platform: adc
    pin: A0
    name: "Battery"
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - multiply: 5.1817

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s

safe_mode:
  boot_is_good_after: 1ms
  num_attempts: 10
